Resources/translations/messages.fa.yml
Hi,
Here is the Persian translation. I will be glad if you include it in your next versions. :smile:
=> Persian Translation

Resources/translations/messages.nl.yml
Created the translations (messages.nl.yml) for the Dutch language.
=> Dutch translation

Datatable/Column/MultiselectAction.php, Resources/views/Datatable/options.html.twig
add icon attribute to MultiselectAction - icons needed
add escape js in options.html.twig for dom - now it is possible use double quotes
=> small improvement

Datatable/Column/AbstractColumn.php, Datatable/Column/BooleanColumn.php, Datatable/Column/Column.php, Datatable/Column/TimeagoColumn.php, Datatable/Data/DatatableDataManager.php, Datatable/Data/DatatableQuery.php, Datatable/View/AbstractDatatableView.php, Datatable/View/Options.php, Resources/doc/columns.md, Resources/doc/example.md, Resources/views/Datatable/datatable_html.html.twig, Resources/views/Datatable/datatable_js.html.twig, Resources/views/Filters/filter_select.html.twig, Resources/views/Filters/filter_text.html.twig, Twig/DatatableTwigExtension.php
- different comparison feature is added (like, eq, in, etc.)
- dropdown-like filter rendering with custom options list is implemented (options as custom array, options as properties values of other entity).
You can check out these feature at your example project: https://github.com/dchabanenko/dtbundle-demo/tree/custom-filters
=> Custom filters implementation #29

Datatable/Column/BooleanColumn.php, Resources/doc/example.md, Resources/views/Datatable/datatable_js.html.twig, Resources/views/Filters/filter_select.html.twig
fixes for custom filters on the datatable header, related to issue #29
=> custom filters fix #29

Command/GenerateDatatableCommand.php
Enable template inheritance for Datatable class generation via command.
This is a more or less copy from SensioBundle with updated path and bundle name.
Sensio\Bundle\GeneratorBundle\Command\GeneratorCommand
=> Update Generator SkeletonDirs for inheritance

Resources/doc/options.md
=> Fixed # Options / order Default value

Resources/views/Filters/filter_select.html.twig
=> Fixed double selected attribute in filter_select caused by '' and '0' options

Datatable/View/Options.php, Resources/doc/bootstrap3.md, Resources/views/Datatable/options.html.twig
In case you want to use integration options, but still want to define your own dom, there should be a way to force it. here it is :)
=> add force_dom option

Resources/translations/messages.ru.yml, Resources/views/Datatable/datatable_js.html.twig
Translate the bundle to Russian
Fixed behaviour filter in server-side mode
=> Several small fixes

Resources/translations/messages.es.yml
Update Spanish translation according to issue #270
=> Update Spanish translation (messages.es.yml)

Resources/translations/messages.fr.yml
Update French translation (relative to #270)
=> Update French translation (messages.fr.yml)

Command/GenerateDatatableCommand.php
See https://github.com/stwe/DatatablesBundle/issues/289#issuecomment-190304636
=> get generator

Datatable/View/AbstractDatatableView.php, Resources/doc/setup.md
It adds a validation check for the output of the ``getName`` method.
Closes #308
Ping @stwe
=> [#308] Added a validation for the output of the getName method for a datatable

Resources/views/Datatable/datatable_js.html.twig, Resources/views/Datatable/render_functions.html.twig
This is a possible solution to #305.
=> In place editing available in child rows when responsive extension is active.

Resources/doc/installation.md, Resources/translations/messages.pt.yml
=> Add pt translations

Datatable/Data/DatatableQuery.php, Resources/doc/query.md
=> Add response callbacks

Resources/translations/messages.pl.yml
Just updated polish translations.
=> Polish translations updated

Resources/translations/messages.ru.yml
Update Russian translations according to #270
=> Update Russian translations

Datatable/Data/DatatableQuery.php
=> Add check for callable in setters

Resources/translations/messages.ru.yml
=> error of syntax translation in Russian

Datatable/View/Callbacks.php
in order to allow parameters and make this file compatible with callbacks.html.twig
=> Udating Callbacks.php to allow parameters

Resources/translations/messages.tr.yml
=> Create Turkish Lang

Resources/views/datatable/language.html.twig
To stay compatible with locale set as en_GB or en_US...
=> Fix CDN option key and force locale to 2 chars

Response/DatatableQueryBuilder.php, Response/DatatableResponse.php
Doctrine Paginator already make a DISTINCT COUNT query
=> Use Doctrine Paginator Count instead of making another query

Datatable/OptionsTrait.php
Resolves https://github.com/stwe/DatatablesBundle/issues/607
=> Encode empty arrays too

Datatable/Column/ActionColumn.php
Fixes issue https://github.com/stwe/DatatablesBundle/issues/657
=> Fix ActionColumn route parameters handling

Resources/views/datatable/datatable_js.html.twig
Fixes issue https://github.com/stwe/DatatablesBundle/issues/655
=> Register events before datatable get initialized

.travis.yml, Controller/DatatableController.php, Resources/config/services.yml, Resources/doc/installation.md, composer.json
=> Adding Symfony 4 support

Datatable/Extension/RowGroup.php, Datatable/Extensions.php, Resources/doc/extensions.md, Resources/views/datatable/extensions.html.twig
Impemented the RowGroup extension which has the ability to group rows in a table.
=> RowGroup extension

CHANGELOG.md, Datatable/Filter/AbstractFilter.php, Datatable/Filter/DateRangeFilter.php
As supposed by @agatagolebiowska in #803.
=> Fix DateRangeFilter

Datatable/Column/NumberColumn.php, Resources/doc/columns.md
Hi,
I added a NumberColumn option suffix_string. This option allows to display a string after the value.
=> Add suffix_string parameter in NumberColumn

Datatable/Column/NumberColumn.php, Resources/doc/columns.md
Reverts stwe/DatatablesBundle#834
=> Revert "Add suffix_string parameter in NumberColumn"

Datatable/Filter/AbstractFilter.php, Datatable/Options.php
[From this issue](https://github.com/stwe/DatatablesBundle/issues/848)
=> Adding like% and %like in filter

Datatable/Column/ArrayColumn.php, Datatable/Filter/AbstractFilter.php, Resources/doc/columns.md, Tests/Column/ArrayColumnTest.php
This feature allow us to define colum for arrays + output them in a formatted way
=> ArrayColumn feature + docs + allow search array values

Datatable/Column/AbstractColumn.php, Datatable/Column/ActionColumn.php, Datatable/Column/ArrayColumn.php, Datatable/Column/AttributeColumn.php, Datatable/Column/BooleanColumn.php, Datatable/Column/Column.php, Datatable/Column/ColumnInterface.php, Datatable/Column/DateTimeColumn.php, Datatable/Column/ImageColumn.php, Datatable/Column/NumberColumn.php, Response/DatatableFormatter.php, Response/DatatableQueryBuilder.php, Tests/Datatables/PostDatatable.php
Reverts stwe/DatatablesBundle#914
=> Revert "Add attributes mapped, is_association and data_source"

Datatable/Filter/SelectFilter.php, Response/DatatableQueryBuilder.php
it's possible for a null value to sneak through "addAndExpression", fixes #936
=> Update DatatableQueryBuilder.php to fix #936 (null value in setSelectSearchType)

Response/DatatableQueryBuilder.php
fixes #970 #963 
The problem exists since this commit:
https://github.com/stwe/DatatablesBundle/commit/a45a8e403a4bcd4501284ec9cf782475a0d3b8ae
=> Fix individual filtering on VirtualColumn

Controller/DatatableController.php
switched from deprecated constants in Doctrine\DBAL\Types\Type to suggested replacements in Doctrine\DBAL\Types\Types
=> Fix doctrine DBAL 3 compatibility
