- Resources/views/Datatable/datatable_html.html.twig
The javascript relies on a tfoot in the html. The tfoot was only displayed if individual filtering was disabled. With this fix it's not the case anymore.
> Fix show multiselect actions even when individual filtering is disabled

- Datatable/View/Options.php
Hello,
Migrating from 0.6.1 to 0.7, I found that setOptions is overriding possible previous calls of setOptions. It may be interesting to add a function setOption in order to have the same behaviour as "setParameters" and "setParameter" in Doctrine.
It is useful if you use a "BaseDatatable" which sets the default options using setOptions. Then you can extend BaseDatatable for your datatables and set the specific options one by one.
> Add possibility to set only one option

- Resources/views/Datatable/datatable_js.html.twig
This problem occurs because the selector $(selector + '_wrapper thead tr') returns two rows (expected one): one is the table names, another is hidden (with zero height). 
The simple solution might be to insert the filters row after the last row in header, like this:
$(selector + '_wrapper tfoot tr').clone().insertAfter($(selector + '_wrapper thead tr').last());
> #157 fixed filter appearing twice on clientside mode

- Datatable/Column/BooleanColumn.php
- Datatable/Column/Column.php
- Datatable/Column/TimeagoColumn.php
- Datatable/View/AbstractDatatableView.php
- Datatable/View/Options.php
- Resources/doc/example.md
- Resources/views/Skeleton/class.php.twig
- Twig/DatatableTwigExtension.php
Changed every short array syntax to traditional array syntax to avoid
problems with projects using PHP 5.3
I used PHPStorm, changed PHP inspections to 5.3, run inspection 'short array syntax is only allowed in PHP 5.4 or above' and now it doesn't find any problem with short arrays so it should certainly be fixed.
> Reverted from short array syntax to traditional

- Resources/views/Datatable/features.html.twig
scrollY is a string instead of a boolean so the value should be inserted
https://datatables.net/reference/option/scrollY
> fixed scrollY has wrong type in twig

- Resources/views/Action/actions_string.html.twig
Because, sometimes, you have markup in your datatable cells
> render_if compares to raw value

- Datatable/Data/DatatableQuery.php
I was trying this:
```
->add('my_field', 'boolean', array(
'searchable' => true,
'visible' => true,
'search_type' => 'isNotNull',
))
````
and it wasn't working
so I gave a look at the source, and noticed that the condition should be
```
$andExpr->add($pivot->expr()->isNotNull($searchField));
```
I didn't look all the code, but this is working now
> fix isNotNull() in case 'isNotNull':

- Resources/views/Datatable/datatable_js.html.twig
Add searchDelay option to individual column filtering with the "throttle" util from Datatable API.
> Add searchDelay to individual column filtering

- Resources/views/Datatable/editable.html.twig
Fixed the x-editable problem (#269) specifying the container attribute as something outside of the table (e.g. body).
> [#269] Fixed x-editable box problem (hidden by the table) when scroll-x=true.

- Datatable/Column/AbstractColumn.php
- Datatable/Column/ColumnInterface.php
- Datatable/Data/DatatableQuery.php
- Resources/doc/columns.md
Hello,
I had to create a custom column to show some complex template (like you did for the `image` column and the `ii_render_image.html.twig` / `render_image.html.twig`).
I introduced a new `getHelperTemplate` method in the `AbstractColumn`. 
The entry point is in `DatatableQuery`::`getResponse()` method:
```php
...
/** @var Column $column */
if (null !== $column->getHelperTemplate()) {
$_data = $item;
foreach($columnNames = explode('.', $data) as $part) {
$_data = $_data[$part];
}
$item[implode('_', $columnNames)] = $this->twig->render($column->getHelperTemplate(), [
'data' => $_data,
'column' => $column
]);
}
...
```
You can notice we render the helper template with the `data value` (ex. `name` value or `client.name` value in a `ManyToOne` case) and the whole `column` instance so you'll …
> implements helper templates

- DependencyInjection/Compiler/DatatableViewPass.php
- Resources/config/services.yml
- Resources/doc/installation.md
Fixes #322 
I've added a user deprecation notice into the compiler pass to not break BC.
Should be removed in a future version
> use parent service instead of tagging datatables view class

- Resources/views/Datatable/ajax.html.twig
raw url twig output to avoid htmlentities chars with GET params
> raw url twig output

- Resources/views/Helper/ii_render_image.html.twig
Template **ii_render_image.html.twig** not work with **imagine_filter**. remove asset function to work fine with liipImagine bundle
> remove asset function on elements that use imagine_filter

- Resources/views/Filters/filter_daterange.html.twig
- Resources/views/Filters/filter_text.html.twig
Hello
I need restoring the filter values after page refresh. The Datatable successfully load the filter values from local storage and make server-side query. This working perfect. But inputs (input.individual_filtering and etc.) not restore own values. I don't find solution better than the state_load_param callback.
```
function (settings, data)
{
try {
if (data) {
data.columns.forEach(function(column, i, columns) {
var object = $("#{{view_table_id}} .individual_filtering[data-filter-property-id="+i+"]");
if (!object) {
return;
}
if (object.is("select")) {
object.select2("val", column.search.search);
} else if (object.is("input")) {
object.val(column.search.search);
}
});
}
} catch (e) {
console.log(e);
}
}
```
You can see what i use the data-filter-property-id attribute for mapping the …
> Adds attribute data-filter-property-id for all filters

- Datatable/Data/DatatableQuery.php
Callback should be validated against callable either in setters or just before attempt to call callback.
For example
```
$query->addWhereAll(1);
```
will fail because integer given and callable expected there.
we can fix it for methods with callbacks like
```
public function addWhereAll(callable $callback)
```
or as alternative check for callable before call like
```
is_callable($callback) && $callback($qb);
```
I'd prefer type hinting in method signatures
> Add type hinting for DatatableQuery callables

- Resources/doc/filter.md
Since https://github.com/stwe/DatatablesBundle/commit/e27449ddde744e3d1f9f9816b452f1d05cbda2ac#diff-019f674683109670b7f0f02edff28b82R204
The default `individual_filtering_position` option is `head`
> Updated doc

- Datatable/Column/ImageColumn.php
- Resources/doc/columns.md
- Resources/views/Helper/ii_render_image.html.twig
in `Resources/views/Helper/ii_render_image.html.twig`, when the `enlarge` config is true, a modale opens and show the image without filter, the new `imagineFilterEnlarged` parameter allow us to set a filter for this picture which might be really big (true story) and kill some cats.
> add imagineFilterEnlarged parameter

- Resources/views/Datatable/callbacks.html.twig
Example of use:
$this->callbacks->set(array(
'row_callback' =>array('ProcesosGeneralesBundle:callbacks:row.js.twig',array('userID'=>$options['userID']))
));
------ row.js.twig ----
function rowCallback(nRow, aData, index) {
/*nRow, aData, index*/
/*console.log(aData);*/
var userID = "{{userID}}";
var $nRow = $(nRow);
if (userID=="2") {
$nRow.css({color: "red"});
}
return nRow;
}
> Sending parameters to callback views

- Datatable/Column/ColumnBuilder.php
- Datatable/Data/DatatableQuery.php
- Resources/doc/columns.md
This is an improvement based on the pull request discussed [here](https://github.com/stwe/DatatablesBundle/pull/391) from foaly-nr1
In order to add an embedded column in a datatable, it should be separated with `\\.`
example: 
```php
$this->columnBuilder
->add('id', 'column', array(
'visible' => false,
))
->add('checkbox', 'virtual', array(
'title' => '',
))
->add('credentials\\.username', 'column', array( // this is an embeddable named "Credentials"
'title' => 'Username',
))
;
```
> Added support for embeddables

- Tests/Datatables/PostDatatable.php
According to [the docs](https://github.com/stwe/DatatablesBundle/blob/master/Resources/doc/setup.md#top-actions-options) and source code, the required top actions option `actions` does not have a default value.
The test there must fail. See: https://travis-ci.org/stwe/DatatablesBundle/builds/134536171
> Set required topActions option actions

- Datatable/Data/DatatableQuery.php
If there are no WHERE statements, then `recordsTotal === recordsFiltered`. In that case, there is no need to run two (exactly the same) queries.
> Prevent duplicate query

- Resources/views/Datatable/render_functions.js.twig
I wanted to be able to add my own render functions to the existing ones. Bundle inheritance is the obvious way to do this. So in my `app/Resources` directory I added `SgDatatablesBundle/views/Datatable/render_functions.js.twig` and proceeded to try to extend `render_functions.js.twig`.
But because the original template contains no blocks, I could not extend it.  I've added an enclosing block to the template. Now, if you want to extend it, it's just a case of doing something like this:
````
{% extends 'SgDatatablesBundle:Datatable:render_functions.js.twig' %}
{% block renderFunctions %}
parent();
function render_list( data, type, row, meta ) {
if (!data) return '';
var ul = '<ul class="list-unstyled"><li>' + data.join('</li><li>') + '</li></ul>';
return ul;
};
{% endblock renderFunctions …
```
> add block to render_functions.js.twig so bundle

- Resources/views/Action/multiselect_actions.html.twig
added support for indeterminated checkAll
also fixes scenario, where checkAll was still being ticket, when u ticketed checkAll and after that deselected at least one row
> added support for indeterminated checkAll and minor fix

- Tests/DatatableTest.php
- Tests/Datatables/PostDatatable.php
1. Generating a route `post_results` will fail as there is no such route in this bundle.
2. The option `id` does not exist. This seems to be a typo.
The errors were not previously thrown as `buildDatatable()` was never called.
> Call buildDatatable() in DatatableTest

- Resources/doc/columns.md
This is a suggestion on extending the column documentation as mentioned in https://github.com/stwe/DatatablesBundle/issues/454.
There are still some open issues e.g.:
> update documentation on columns

- Datatable/Data/DatatableQuery.php
The changed introduced in https://github.com/stwe/DatatablesBundle/pull/393 allow embeddables as columns. This pull request addresses an issue that leads to an exception when one these columns is used to order by.
> Support embeddables in order columns

- Response/DatatableQueryBuilder.php
Now correctly calls one of QueryBuilder's join functions
> Fixed crash on joins in DatatableQueryBuilder

- Response/DatatableQueryBuilder.php
- Tests/DatatableTest.php
Using the database table name result in weird alias name for the base entity if table name is different from entity name (when using prefix).
This is not very intuitive when we want to manually modify the queryBuilder, because, the base entity will use the table name, and joins ar using entities names.
Example:
```php
/**
* @ORM\Table(name="Prefix_Entity")
* @ORM\Entity
*/
class Entity {
private $id;
private $name;
private $joinColumn;
}
/**
* @ORM\Table(name="Prefix_Join")
* @ORM\Entity
*/
class Join {
private $id;
private $name;
}
// Before
// SELECT partial prefix_entity.{id,name}, partial join.{id,name} 
// FROM Entity prefix_entity LEFT JOIN prefix_entity.join join
// After
// SELECT partial entity.{id,name}, partial join.{id,name} 
// FROM Entity entity LEFT JOIN entity.join join …
```
> Use the entity class name instead of the database table name

- Datatable/Column/AbstractColumn.php
```php
'type_of_field' => 'integer'
```
throw an exception:
> The option "type_of_field" with value "integer" is invalid. Accepted values are: null, array.
> Fix type_of_field allowed values

- Response/DatatableQueryBuilder.php
Negative number are not properly ordered.
ABS function return the absolute value, so negative numbers become positive which result in an incoherent sorting.
Before:
`0, 1, -2, 4, -5, 8`
After:
`-5, -2, 0, 1, 4, 8`
The only way to order string/varchar database fields as numbers is to cast them.
Doctrine do not provide cast function, so the user have to implement it if needed, and use it with a custom DQL => https://github.com/stwe/DatatablesBundle/pull/551
> Fix integers order by

- Datatable/Column/ActionColumn.php
We will be able to add new actions on previously created `ActionColumn`. (Useful when extending a Datatable class)
> Add action method on ActionColumn

- Response/DatatableResponse.php
I have a performance problem because it is not possible to change the $ fetchJoinColumn parameter when the Doctrine\ORM\Tools\Pagination\Paginator instance is created :( . 
According to [pagination](http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/tutorials/pagination.html) this behavior is only necessary if you actually fetch join to-many collection, (in my case many-to-one). 
By the way awsome work. 👍
> Add: allow set fetchJoinCollection on getResponse method

- Datatable/Column/ColumnBuilder.php
Reindex columns array on column remove to prevent global search issue when a column is removed from the datatable.
> Reindex columns on column remove

- Resources/doc/cache.md
- Resources/doc/installation.md
- Resources/doc/query.md
- Response/DatatableQueryBuilder.php
Count lines from the current query builder instead of counting all lines from the table.
`buildQuery()` is no longer used. But you can call `getBuiltQb()` if you want to access to the built query for any reason (like debug purpose).
> Fix recordsTotal count

- Resources/doc/query.md
Replaced `$isAjax` by `$request->isXmlHttpRequest()`
> Replaced `$isAjax` by `$request->isXmlHttpRequest()` in documentation

- composer.json
This package requires `"friendsofsymfony/jsrouting-bundle": "1.6.0"`, while there is a bugfix release available.
I've updated other dependencies too, to have a consistent syntax. This has no impact on the required version because `^1.0 === ~1.0`
> Use caret operator for composer dependencies

- composer.json
Allow to use friendsofsymfony/jsrouting-bundle in v2
> Allow to use friendsofsymfony/jsrouting-bundle in v2

- Datatable/Column/MultiselectColumn.php
- Resources/translations/messages.sk.yml
Symfony 4's PropertyAccessor uses primary add* method for adding properties, not set*. Since MultiselectColumn is derived from ActionColumn and MultiselectColumn didn't have a addAction method, PropertyAccessor uses addAction method from ActionColumn class, that creates Action objects, not MultiselectAction objects.
> Fix for Multiselect Column on Symfony 4

- Resources/views/datatable/search.js.twig
Fix individual filtering in combination with horizontal scrolling byusing the Datatable instance and not a predefined ID as selector.
Bug: When individual filtering used on a table with `scrollX = true` the column filters don't work. The code in search.js.twig searches for the input & select fields in the datatable (by the id of the table). Because of the scrollX, the table has been split up in 2 different tables (e.g. one table for scrollHead and another table for scrollBody). The input fields are now outside the 'selector' and will not work. 
To solve this the selector should be changed to the wrapper/container. However this is different for tables with or without scrollX. Like the example on https://datatables.net/extensions/fixedcolumns/examples/styling/col_filter.html I've now used …
> Fix individual filtering in combination with scrollX

- README.md
This project hasn't been analyzed for 1,5 years, so it makes no sense to keep this badge.
> Removed SymfonyInsight label

- .travis.yml
- composer.json
PHP 5.4, 5.5 and 7.0 are End Of Life (EOL) now, 5.6 will be in a month.
Developers working with PHP 5 or PHP 7.0 should be banned from the community as soon as possible ;).
> Drop PHP < 7.1

- Datatable/Column/DateTimeColumn.php
Fixes the problem reported in #812 and #883
When the array is null, the count finction in PHP 7.2 an hight stop working. With the null check in the if clause, the problem is solved and run like it should.
> Added null test for PHP > 7.1

- Resources/translations/messages.fr.yml
Fix of #722 
Date range is not working in fr local right now.
This is probably not the best way, but because we use daterange picker to select date range, for me it's not a big issue to have date in english format.
> Fixing DateTime::__construct() issue for french local

- Controller/DatatableController.php
Sensio\Bundle\FrameworkExtraBundle\Configuration\Method and Route have been deprecated in 4.1+
Fixed with new Symfony\Component\Routing\Annotation\Route for 4.1+
HOWEVER, with this change, older code would break.
> Fixed deprecated Route annotation

- Controller/DatatableController.php
According to Symfony documentation, right property name for specifying methods is "methods", not "method". It also throws me an exception:
> An exception has been thrown during the rendering of a template ("Unknown property "method" on annotation "Symfony\Component\Routing\Annotation\Route" in .../vendor/sg/datatablesbundle/Controller/ (which is being imported from ".../config/routes/sg_datatables_bundle.yaml"). Make sure annotations are installed and enabled.").
> Fix unknown property "method" on Route annotation

- Datatable/Column/AttributeColumn.php
- Resources/doc/columns.md
- Resources/views/render/attributeColumn.html.twig
Hi,
I added the AttributeColumn which allows to create a column in which every cell contains a span tag with data-* attributes passed as parameters.
> Add an AttributeColumn with data-* attributes

- Datatable/Column/AbstractColumn.php
- Resources/doc/columns.md
- Resources/views/column/column.html.twig
- Resources/views/datatable/columns.html.twig
- Resources/views/datatable/datatable_html.html.twig
- Resources/views/datatable/datatable_js.html.twig
- Response/DatatableFormatter.php
Hi,
I added a column option `sent_in_response`. By default this option is set to `true`. But if you set it to `false`, it allows to get a field from the table, but without sending this field to the browser. This allows to access to this field in closures used in the options of other columns for instance.
The `visible` option isn't sufficient here, because it's only hide columns in browser, and user can show them.
> Get fields from database without sending them to browser

- Response/DatatableQueryBuilder.php
Further improvement of pull request 736, now also prefix table name alias uses in joins.
> Add _ prefix to reserved joined table name alias

- Datatable/Filter/AbstractFilter.php
Pushing https://github.com/stwe/DatatablesBundle/pull/870 has made reappear the issue https://github.com/doctrine/doctrine2/issues/6363.
I have reproduce trying something like that:
`    $this->columnBuilder->add('structurePath', Column::class, array(
'title' => 'structure path',
'searchable' => true,
'dql' => '(SELECT GROUP_CONCAT({s}.label SEPARATOR \' \') FROM '.Structure::class.' {s} WHERE {s}.lft <= structure.lft and {s}.rgt >= structure.rgt and {s}.root = structure.root)',
'type_of_field' => 'string',
'filter' => array(TextFilter::class, array(
'search_type' => 'like%',
))
));
` 
So I suggest this correction according to the existing solution.
> Correction adding like% and %like in filter

- Datatable/Extension/RowGroup.php
Fixes the use of the undefined `$startRender` variable by using the original argument variable `$endRender`.
> [FIX] extension: RowGroup use end renderer argument variable

- Datatable/Filter/AbstractFilter.php
The json_array type is deprecated, so I've added the json type:
https://www.doctrine-project.org/projects/doctrine-dbal/en/2.7/reference/types.html#json
> Allow string search in json type fields
